services:
  llonebot-docker:
    image: garrise/ll-cc-docker
    tty: true
    container_name: ll-cc-docker
    restart: always
    ports:
      - "5900:5900"       #vnc默认端口
      - "6081:6081"       #noVNC默认端口
      - "5500:5500"
      - "3000:3000"       #LLOneBot正向Websocket接口
      - "3001:3001"       #LLOneBot反向Websocket接口
      - "3301:3301"       #Chronocat反向Websocket接口
    environment:
      - TZ=Asia/Shanghai
      - VNC_PASSWD=vncpasswd
    volumes:
      - ./LiteLoader/:/opt/QQ/LiteLoader/
      # 未固化QQ数据 当前仅固化LiteLoader
